In [1]:
dictionary = {}

In [2]:
dictionary['key'] = 'value'

In [3]:
dictionary

{'key': 'value'}

In [4]:
ls = [1,2,3,4]

In [5]:
dictionary['ls'] = ls

In [6]:
dictionary.update({'ls': ls})

In [8]:
dictionary

{'key': 'value', 'ls': [1, 2, 3, 4]}

In [9]:
ls.append(5)

In [10]:
ls

[1, 2, 3, 4, 5]

In [11]:
dictionary

{'key': 'value', 'ls': [1, 2, 3, 4, 5]}

In [12]:
from copy import deepcopy

In [13]:
dictionary.update({'ls': deepcopy(ls)})

In [15]:
dictionary

{'key': 'value', 'ls': [1, 2, 3, 4, 5]}

In [16]:
ls.append(6)

In [17]:
ls

[1, 2, 3, 4, 5, 6]

In [18]:
dictionary

{'key': 'value', 'ls': [1, 2, 3, 4, 5]}

In [19]:
dictionary.setdefault('ls', [])

[1, 2, 3, 4, 5]

In [20]:
dictionary

{'key': 'value', 'ls': [1, 2, 3, 4, 5]}

In [21]:
{
    'a': {
        'b': 'c'
    }
}

{'a': {'b': 'c'}}

In [22]:
dictionary.setdefault('a', {}).setdefault('b', 'c')

'c'

In [23]:
dictionary

{'key': 'value', 'ls': [1, 2, 3, 4, 5], 'a': {'b': 'c'}}

In [24]:
def setdefault(d, k, v):
    if k in d:
        return d
    d[k] = v
    return d

In [25]:
dictionary.items()

dict_items([('key', 'value'), ('ls', [1, 2, 3, 4, 5]), ('a', {'b': 'c'})])

In [26]:
dictionary.keys()

dict_keys(['key', 'ls', 'a'])

In [27]:
dictionary.values()

dict_values(['value', [1, 2, 3, 4, 5], {'b': 'c'}])

In [28]:
dictionary

{'key': 'value', 'ls': [1, 2, 3, 4, 5], 'a': {'b': 'c'}}

In [33]:
value = dictionary.pop('key', None)

In [34]:
value

In [36]:
list(dictionary.keys())

['ls', 'a']

In [37]:
nd = {'key': 'shubham'}

In [38]:
nd

{'key': 'shubham'}

In [39]:
d = {**dictionary, **nd}

In [40]:
d

{'ls': [1, 2, 3, 4, 5], 'a': {'b': 'c'}, 'key': 'shubham'}

In [49]:
t = ('a', 'b')
c = ('c', 'd')

In [50]:
ls_with_t = [t, t, t, c]

In [51]:
ls_with_t

[('a', 'b'), ('a', 'b'), ('a', 'b'), ('c', 'd')]

In [52]:
dict(ls_with_t)

{'a': 'b', 'c': 'd'}

In [54]:
list(range(5))

[0, 1, 2, 3, 4]

In [56]:
list(reversed(range(5)))

[4, 3, 2, 1, 0]

In [59]:
tuples = list(zip(list(range(5)), list(reversed(range(5)))))
print(tuples)

[(0, 4), (1, 3), (2, 2), (3, 1), (4, 0)]


In [61]:
mappings = dict(tuples)
print(mappings)

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}


In [63]:
mappings.get('5', 0)

0

In [64]:
words = ["apple", "bat", "bar", "atom", "book"]

In [69]:
word_dict = {}

for word in words:
    first_letter = word[0]
    if first_letter not in word_dict:
        word_dict[first_letter] = [word]
    else:
        word_dict[first_letter].append(word)

print(word_dict)

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}


In [75]:
word_dict = {}

for word in words:
    first_letter = word[0]
    word_dict.setdefault(first_letter, []).append(word)
    print(word_dict)

print(word_dict)

{'a': ['apple']}
{'a': ['apple'], 'b': ['bat']}
{'a': ['apple'], 'b': ['bat', 'bar']}
{'a': ['apple', 'atom'], 'b': ['bat', 'bar']}
{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}
{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}


In [76]:
from collections import defaultdict

In [87]:
word_dict = defaultdict(list)

In [88]:
for word in words:
    word_dict[word[0]].append(word)

print(dict(word_dict))

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}


In [89]:
d = {}

In [90]:
d['s'] = 'string'
d[1] = 2
d[(1,2)] = 3

In [92]:
hash('s')

-871183290662278430

In [93]:
strings = ["a", "as", "bat", "car", "dove", "python"]

In [94]:
loc_mapping = {value: index for index, value in enumerate(strings)}
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

In [96]:
a = None

In [99]:
def bind_a_variable():
    global a
    a = 6
bind_a_variable()

In [100]:
a

6

In [101]:
def f():
    a = 5
    b = 6
    c = 7
    return a, b, c

In [103]:
return_value = f()
return_value

(5, 6, 7)

In [105]:
states = ["Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda", 
                   "south  carolina##", "West virginia?"]

In [108]:
import re

def remove_punctuations(value):
    return re.sub("[!#?]", "", value)

clean_ops = [str.strip, remove_punctuations, str.title]
def clean_strings(strings, ops):
    result = []
    for value in strings:
        for func in ops:
            value = func(value)
        result.append(value)
    return result

In [109]:
clean_strings(states, clean_ops)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South  Carolina',
 'West Virginia']

In [110]:
strings = ["foo", "card", "bar", "aaaa", "abab"]

In [115]:
strings.sort(key=lambda x: len(set(x)))
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

In [116]:
def squares(n=10):
    print(f"Generating squares from 1 to {n ** 2}")
    for i in range(1, n + 1):
        yield i ** 2

In [124]:
gen = squares(20)
gen

<generator object squares at 0x7fad0eca6500>

In [125]:
for x in gen:
    print(x, end=" ")

Generating squares from 1 to 400
1 4 9 16 25 36 49 64 81 100 121 144 169 196 225 256 289 324 361 400 

In [130]:
import itertools
comb = itertools.combinations(range(4), 3)
comb

In [135]:
import numpy as np

In [136]:
my_arr = np.arange(1_000_000)

In [140]:
my_list = list(range(1_000_000))

In [138]:
%timeit my_arr2 = my_arr * 2

788 µs ± 29.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [141]:
%timeit my_list2 = [x * 2 for x in my_list]

25.8 ms ± 315 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [142]:
data1 = [6, 7.5, 8, 0, 1]

In [143]:
arr1 = np.array(data1)

In [144]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [145]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [146]:
arr2 = np.array(data2)

In [147]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [148]:
arr2.ndim

2

In [149]:
arr2.shape

(2, 4)

In [150]:
arr1.dtype

dtype('float64')

In [152]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [153]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [154]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [155]:
rng = np.random.default_rng(seed=12345)

In [156]:
data = rng.standard_normal((2, 3))

In [157]:
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [1]:
print(2)

2


In [6]:
import numpy as np



def func_gen():
    for i in np.arange(1000):
        if i % 4 == 0:
            yield i

def func():
    ls = []
    for i in np.arange(1000):
        if i % 4 == 0:
            ls.append(i)
    return ls


In [9]:
func() # memory intensive if called multiple times

[0,
 4,
 8,
 12,
 16,
 20,
 24,
 28,
 32,
 36,
 40,
 44,
 48,
 52,
 56,
 60,
 64,
 68,
 72,
 76,
 80,
 84,
 88,
 92,
 96,
 100,
 104,
 108,
 112,
 116,
 120,
 124,
 128,
 132,
 136,
 140,
 144,
 148,
 152,
 156,
 160,
 164,
 168,
 172,
 176,
 180,
 184,
 188,
 192,
 196,
 200,
 204,
 208,
 212,
 216,
 220,
 224,
 228,
 232,
 236,
 240,
 244,
 248,
 252,
 256,
 260,
 264,
 268,
 272,
 276,
 280,
 284,
 288,
 292,
 296,
 300,
 304,
 308,
 312,
 316,
 320,
 324,
 328,
 332,
 336,
 340,
 344,
 348,
 352,
 356,
 360,
 364,
 368,
 372,
 376,
 380,
 384,
 388,
 392,
 396,
 400,
 404,
 408,
 412,
 416,
 420,
 424,
 428,
 432,
 436,
 440,
 444,
 448,
 452,
 456,
 460,
 464,
 468,
 472,
 476,
 480,
 484,
 488,
 492,
 496,
 500,
 504,
 508,
 512,
 516,
 520,
 524,
 528,
 532,
 536,
 540,
 544,
 548,
 552,
 556,
 560,
 564,
 568,
 572,
 576,
 580,
 584,
 588,
 592,
 596,
 600,
 604,
 608,
 612,
 616,
 620,
 624,
 628,
 632,
 636,
 640,
 644,
 648,
 652,
 656,
 660,
 664,
 668,
 672,
 676,
 680,
 6

In [11]:
list(func_gen()) # memory efficient

[0,
 4,
 8,
 12,
 16,
 20,
 24,
 28,
 32,
 36,
 40,
 44,
 48,
 52,
 56,
 60,
 64,
 68,
 72,
 76,
 80,
 84,
 88,
 92,
 96,
 100,
 104,
 108,
 112,
 116,
 120,
 124,
 128,
 132,
 136,
 140,
 144,
 148,
 152,
 156,
 160,
 164,
 168,
 172,
 176,
 180,
 184,
 188,
 192,
 196,
 200,
 204,
 208,
 212,
 216,
 220,
 224,
 228,
 232,
 236,
 240,
 244,
 248,
 252,
 256,
 260,
 264,
 268,
 272,
 276,
 280,
 284,
 288,
 292,
 296,
 300,
 304,
 308,
 312,
 316,
 320,
 324,
 328,
 332,
 336,
 340,
 344,
 348,
 352,
 356,
 360,
 364,
 368,
 372,
 376,
 380,
 384,
 388,
 392,
 396,
 400,
 404,
 408,
 412,
 416,
 420,
 424,
 428,
 432,
 436,
 440,
 444,
 448,
 452,
 456,
 460,
 464,
 468,
 472,
 476,
 480,
 484,
 488,
 492,
 496,
 500,
 504,
 508,
 512,
 516,
 520,
 524,
 528,
 532,
 536,
 540,
 544,
 548,
 552,
 556,
 560,
 564,
 568,
 572,
 576,
 580,
 584,
 588,
 592,
 596,
 600,
 604,
 608,
 612,
 616,
 620,
 624,
 628,
 632,
 636,
 640,
 644,
 648,
 652,
 656,
 660,
 664,
 668,
 672,
 676,
 680,
 6