In [3]:
import pandas as pd
import numpy as np

In [4]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [11]:
obj3 = pd.Series(sdata)

In [12]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [13]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [14]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [15]:
obj4 = pd.Series(sdata, index=states)

In [16]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [19]:
obj4.name = "population"

In [20]:
obj4.index.name = "state"

In [21]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [22]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [23]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]

In [24]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [25]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
"year": [2000, 2001, 2002, 2001, 2002, 2003],
"pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [26]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [27]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [28]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [31]:
pd.DataFrame(data, columns=["year", "state", "pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [32]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [33]:
frame2

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [34]:
frame2["debt"] = 16.5

In [35]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [39]:
frame2["debt"] = np.arange(6.)

In [40]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [42]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])

In [43]:
frame2["debt"] = val

In [44]:
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [45]:
frame2["eastern"] = frame2["state"] == "Ohio"

In [46]:
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [47]:
del frame2["eastern"]

In [48]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [49]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
                "Nevada": {2001: 2.4, 2002: 2.9}}

In [50]:
frame3 = pd.DataFrame(populations)

In [51]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [71]:
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [52]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [53]:
pdata = {"Ohio": frame3["Ohio"][:-1],
        "Nevada": frame3["Nevada"][:2]}

In [54]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [55]:
frame3.index.name = "year"

In [56]:
frame3.columns.name = "state"

In [57]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [58]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [59]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [60]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])

In [61]:
index = obj.index

In [62]:
index

Index(['a', 'b', 'c'], dtype='object')

In [63]:
index[1] = "d"

TypeError: Index does not support mutable operations

In [64]:
labels = pd.Index(np.arange(3))

In [65]:
labels

Index([0, 1, 2], dtype='int64')

In [66]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [67]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [68]:
obj2.index is labels

True

In [69]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [70]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [71]:
"Ohio" in frame3.columns

True

In [72]:
2003 in frame3.index

False

In [105]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [73]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])

In [74]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [75]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])

In [76]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [77]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])

In [78]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [79]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [80]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
        index=["a", "c", "d"],
        columns=["Ohio", "Texas", "California"])

In [81]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [83]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])

In [84]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [85]:
states = ["Texas", "Utah", "California"]

In [86]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [87]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

In [88]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [89]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [90]:
new_obj = obj.drop("c")

In [91]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [92]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [93]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=["Ohio", "Colorado", "Utah", "New York"],
columns=["one", "two", "three", "four"])

In [94]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [95]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [96]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [97]:
data.drop("two", axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [98]:
data.drop(["two", "four"], axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [99]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])

In [100]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [133]:
obj["b"]

1.0

In [101]:
obj[1]

/tmp/ipykernel_8548/2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


1.0

In [120]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [121]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [122]:
obj[[1, 3]]

/tmp/ipykernel_8548/2982346117.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 3]]


b    1.0
d    3.0
dtype: float64

In [123]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [124]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [125]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

In [135]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [136]:
obj1

2    1
0    2
1    3
dtype: int64

In [137]:
obj2

a    1
b    2
c    3
dtype: int64

In [138]:
obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [139]:
obj2[[0, 1, 2]]

/tmp/ipykernel_8548/2599987575.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0, 1, 2]]


a    1
b    2
c    3
dtype: int64

In [140]:
obj2.loc[[0, 1]]

KeyError: "None of [Index([0, 1], dtype='int64')] are in the [index]"

In [141]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [142]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [143]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=["Ohio", "Colorado", "Utah", "New York"],
columns=["one", "two", "three", "four"])

In [144]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [145]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [147]:
data[["three", "one"]]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [148]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [149]:
data[data["three"] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [150]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [151]:
data[data < 5] = 0

In [152]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [153]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [154]:
data.loc[["Colorado", "New York"]]

one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [155]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [156]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [157]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [158]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [159]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [160]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [161]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [162]:
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [163]:
ser = pd.Series(np.arange(3.))

In [164]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [165]:
ser[-1]

KeyError: -1

In [166]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])

In [167]:
ser2[-1]

/tmp/ipykernel_8548/811950851.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]


2.0

In [168]:
ser.iloc[-1]

2.0

In [169]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [170]:
data.loc[:, "one"] = 1

In [171]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [172]:
data.iloc[2] = 5

In [173]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [174]:
data.loc[data["four"] > 5] = 3

In [175]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [176]:
data.loc[data.three == 5, "three"] = 6

In [177]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

In [178]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])

In [179]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
index=["a", "c", "e", "f", "g"])

In [180]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [181]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [182]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [183]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
index=["Ohio", "Texas", "Colorado"])

In [184]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
index=["Utah", "Ohio", "Texas", "Oregon"])

In [185]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [186]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [187]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [188]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
columns=list("abcd"))

In [189]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
columns=list("abcde"))

In [190]:
df2.loc[1, "b"] = np.nan

In [191]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [192]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [193]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [194]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [195]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [196]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [197]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [198]:
arr = np.arange(12.).reshape((3, 4))

In [199]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [200]:
arr[0]

array([0., 1., 2., 3.])

In [201]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [202]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
columns=list("bde"),
index=["Utah", "Ohio", "Texas", "Oregon"])

In [203]:
series = frame.iloc[0]

In [204]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [205]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [206]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [207]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [208]:
series2

b    0
e    1
f    2
dtype: int64

In [209]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [210]:
series3 = frame["d"]

In [211]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [213]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [214]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [215]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
columns=list("bde"),
index=["Utah", "Ohio", "Texas", "Oregon"])

In [216]:
frame

b         d         e
Utah   -0.426338 -1.007643 -0.677594
Ohio    2.219030 -1.056478 -0.424755
Texas   0.725088  0.440385  1.086720
Oregon  0.685583 -1.440727  0.002928

In [217]:
np.abs(frame)

b         d         e
Utah    0.426338  1.007643  0.677594
Ohio    2.219030  1.056478  0.424755
Texas   0.725088  0.440385  1.086720
Oregon  0.685583  1.440727  0.002928

In [218]:
def f1(x):
    return x.max() - x.min()

In [219]:
frame.apply(f1)

b    2.645368
d    1.881112
e    1.764315
dtype: float64

In [220]:
frame.apply(f1, axis="columns")

Utah      0.581305
Ohio      3.275509
Texas     0.646335
Oregon    2.126310
dtype: float64

In [221]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

In [222]:
frame.apply(f2)

b         d         e
min -0.426338 -1.440727 -0.677594
max  2.219030  0.440385  1.086720

In [223]:
def my_format(x):
    return f"{x:.2f}"

In [224]:
frame.applymap(my_format)

/tmp/ipykernel_8548/1462544007.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)


b      d      e
Utah    -0.43  -1.01  -0.68
Ohio     2.22  -1.06  -0.42
Texas    0.73   0.44   1.09
Oregon   0.69  -1.44   0.00

In [225]:
frame["e"].map(my_format)

Utah      -0.68
Ohio      -0.42
Texas      1.09
Oregon     0.00
Name: e, dtype: object

In [226]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])

In [227]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [228]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [229]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
index=["three", "one"],
columns=["d", "a", "b", "c"])

In [230]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [231]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [232]:
frame.sort_index(axis="columns")

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [233]:
frame.sort_index(axis="columns", ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [234]:
obj = pd.Series([4, 7, -3, 2])

In [235]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [236]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [237]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [238]:
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [239]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})

In [240]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [241]:
frame.sort_values("b")

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [242]:
frame.sort_values(["a", "b"])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [243]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [244]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [245]:
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [246]:
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [247]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
"c": [-2, 5, 8, -2.5]})

In [248]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [249]:
frame.rank(axis="columns")

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [250]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])

In [251]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [252]:
obj.index.is_unique

False

In [253]:
obj["a"]

a    0
a    1
dtype: int64

In [254]:
obj["c"]

4

In [255]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),
index=["a", "a", "b", "b", "c"])

In [256]:
df

0         1         2
a  1.417744 -0.982962  1.085156
a  0.314374 -0.946511  0.623252
b  0.723630  1.276071 -0.818090
b -0.119728 -0.477311 -1.718414
c -0.541878  1.184068  1.017740

In [257]:
df.loc["b"]

0         1         2
b  0.723630  1.276071 -0.818090
b -0.119728 -0.477311 -1.718414

In [258]:
df.loc["c"]

0   -0.541878
1    1.184068
2    1.017740
Name: c, dtype: float64

In [259]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
[np.nan, np.nan], [0.75, -1.3]],
index=["a", "b", "c", "d"],
columns=["one", "two"])

In [260]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [261]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [262]:
df.sum(axis="columns")

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [263]:
df.sum(axis="index", skipna=False)

one   NaN
two   NaN
dtype: float64

In [264]:
df.sum(axis="columns", skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [265]:
df.mean(axis="columns")

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [266]:
df.idxmax()

one    b
two    d
dtype: object

In [267]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [277]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [278]:
obj = pd.Series(["a", "a", "b", "c"] * 4)

In [279]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [280]:
price = pd.read_pickle("examples/yahoo_price.pkl")

In [281]:
volume = pd.read_pickle("examples/yahoo_volume.pkl")

In [283]:
returns = price.pct_change()

In [285]:
returns.tail()

AAPL      GOOG       IBM      MSFT
Date                                              
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [286]:
returns["MSFT"].corr(returns["IBM"])

0.4997636114415114

In [287]:
returns["MSFT"].cov(returns["IBM"])

8.870655479703545e-05

In [288]:
returns.corr()

AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [289]:
returns.cov()

AAPL      GOOG       IBM      MSFT
AAPL  0.000277  0.000107  0.000078  0.000095
GOOG  0.000107  0.000251  0.000078  0.000108
IBM   0.000078  0.000078  0.000146  0.000089
MSFT  0.000095  0.000108  0.000089  0.000215

In [290]:
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [292]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

In [293]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [294]:
uniques = obj.unique()

In [295]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [296]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [297]:
pd.value_counts(obj.to_numpy(), sort=False)

/tmp/ipykernel_96198/164454357.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(), sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [298]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [299]:
mask = obj.isin(["b", "c"])

In [300]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [301]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [302]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])

In [303]:
unique_vals = pd.Series(["c", "b", "a"])

In [304]:
indices = pd.Index(unique_vals).get_indexer(to_match)

In [305]:
indices

array([0, 2, 1, 1, 0, 2])

In [306]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
"Qu2": [2, 3, 1, 2, 3],
"Qu3": [1, 5, 2, 4, 4]})

In [307]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [308]:
data["Qu1"].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [309]:
result = data.apply(pd.value_counts).fillna(0)

/tmp/ipykernel_96198/2451317050.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)


In [310]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [311]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})

In [313]:
data

a  b
0  1  0
1  1  0
2  1  1
3  2  0
4  2  0

In [315]:
data.value_counts()

a  b
1  0    2
2  0    2
1  1    1
Name: count, dtype: int64